## CATPUCCIN themed arrows
const
  RESET: string  = "\x1b[0m"
  FG: string = "\x1b[38;2;"
  BG: string = "\x1b[48;2;"

  CATPUCCIN0: string  = "59;66;82m"     #0D1117
  CATPUCCIN1: string  = "69;71;90m"     #45475A
  CATPUCCIN2: string  = "88;91;112m"    #585B70
  CATPUCCIN3: string  = "243;139;168m"  #F38BA8
  CATPUCCIN4: string  = "166;227;161m"  #A6E3A1
  CATPUCCIN5: string  = "249;226;175m"  #F9E2AF
  CATPUCCIN6: string  = "137;180;250m"  #89B4FA
  CATPUCCIN7: string  = "245;194;231m"  #F5C2E7
  CATPUCCIN8: string  = "148;226;213m"  #94E2D5
  CATPUCCIN9: string  = "166;173;200m"  #A6ADC8
  CATPUCCIN10: string  = "250;179;135m" #FAB387
  CATPUCCIN11: string = "245;224;220m"  #F5E0DC
  CATPUCCIN12: string = "180;190;254m"  #B4BEFE
  CATPUCCIN13: string = "203;166;247m"  #CBA6F7
  CATPUCCIN14: string = "116;199;236m"  #74C7EC
  CATPUCCIN15: string = "225;139;138m"  #E18B8A 

  PLINE_0: string = FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0     #0D1117  
  PLINE_1: string = FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1     #45475A 
  PLINE_2: string = FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2     #585B70 
  PLINE_3: string = FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3     #F38BA8 
  PLINE_4: string = FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4     #A6E3A1  
  PLINE_5: string = FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5     #F9E2AF 
  PLINE_6: string = FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6     #89B4FA  
  PLINE_7: string = FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7     #F5C2E7 
  PLINE_8: string = FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8     #94E2D5 
  PLINE_9: string = FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9     #A6ADC8 
  PLINE_10: string = FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10  #FAB387
  PLINE_11: string = FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11  #F5E0DC
  PLINE_12: string = FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12  #B4BEFE 
  PLINE_13: string = FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13  #CBA6F7
  PLINE_14: string = FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14  #74C7EC
  PLINE_15: string = FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15  #E18B8A

  CLINE_0: string = FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0    #0D1117  
  CLINE_1: string = FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1    #45475A  
  CLINE_2: string = FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2    #585B70 
  CLINE_3: string = FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3    #F38BA8 
  CLINE_4: string = FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4    #A6E3A1 
  CLINE_5: string = FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5    #F9E2AF 
  CLINE_6: string = FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6    #89B4FA  
  CLINE_7: string = FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7    #F5C2E7  
  CLINE_8: string = FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8    #94E2D5 
  CLINE_9: string = FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9    #A6ADC8 
  CLINE_10: string = FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10 #FAB387
  CLINE_11: string = FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11 #F5E0DC
  CLINE_12: string = FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12 #B4BEFE
  CLINE_13: string = FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13 #CBA6F7 
  CLINE_14: string = FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14 #74C7EC 
  CLINE_15: string = FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15 #E18B8A


  ALINE_0: string = FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0     #0D1117  
  ALINE_1: string = FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1     #3B4252  
  ALINE_2: string = FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2     #434C5E  
  ALINE_3: string = FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3     #F38BA8  
  ALINE_4: string = FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4     #A6E3A1 
  ALINE_5: string = FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5     #F9E2AF 
  ALINE_6: string = FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6     #89B4FA  
  ALINE_7: string = FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7     #F5C2E7 
  ALINE_8: string = FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8     #94E2D5 
  ALINE_9: string = FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9     #A6ADC8 
  ALINE_10: string = FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10  #FAB387 
  ALINE_11: string = FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11  #F5E0DC
  ALINE_12: string = FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12  #B4BEFE 
  ALINE_13: string = FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13  #CBA6F7 
  ALINE_14: string = FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14  #74C7EC 
  ALINE_15: string = FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15  #E18B8A

  ARROW_0L: string = RESET & FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0     #0D1117  
  ARROW_1L: string = RESET & FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1     #45475A 
  ARROW_2L: string = RESET & FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2     #585B70 
  ARROW_3L: string = RESET & FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3     #F38BA8 
  ARROW_4L: string = RESET & FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4     #A6E3A1  
  ARROW_5L: string = RESET & FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5     #F9E2AF 
  ARROW_6L: string = RESET & FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6     #89B4FA  
  ARROW_7L: string = RESET & FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7     #F5C2E7 
  ARROW_8L: string = RESET & FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8     #94E2D5 
  ARROW_9L: string = RESET & FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9     #A6ADC8 
  ARROW_10L: string = RESET & FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10  #FAB387
  ARROW_11L: string = RESET & FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11  #F5E0DC
  ARROW_12L: string = RESET & FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12  #B4BEFE 
  ARROW_13L: string = RESET & FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13  #CBA6F7
  ARROW_14L: string = RESET & FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14  #74C7EC
  ARROW_15L: string = RESET & FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15  #E18B8A

  ARROW_0R: string = RESET & FG&CATPUCCIN0 & "" & RESET      #0D1117  
  ARROW_1R: string = RESET & FG&CATPUCCIN1 & "" & RESET      #45475A 
  ARROW_2R: string = RESET & FG&CATPUCCIN2 & "" & RESET      #585B70 
  ARROW_3R: string = RESET & FG&CATPUCCIN3 & "" & RESET      #F38BA8 
  ARROW_4R: string = RESET & FG&CATPUCCIN4 & "" & RESET      #A6E3A1  
  ARROW_5R: string = RESET & FG&CATPUCCIN5 & "" & RESET      #F9E2AF 
  ARROW_6R: string = RESET & FG&CATPUCCIN6 & "" & RESET      #89B4FA  
  ARROW_7R: string = RESET & FG&CATPUCCIN7 & "" & RESET      #F5C2E7 
  ARROW_8R: string = RESET & FG&CATPUCCIN8 & "" & RESET      #94E2D5 
  ARROW_9R: string = RESET & FG&CATPUCCIN9 & "" & RESET      #A6ADC8 
  ARROW_10R: string = RESET & FG&CATPUCCIN10 & "" & RESET   #FAB387
  ARROW_11R: string = RESET & FG&CATPUCCIN11 & "" & RESET   #F5E0DC
  ARROW_12R: string = RESET & FG&CATPUCCIN12 & "" & RESET   #B4BEFE 
  ARROW_13R: string = RESET & FG&CATPUCCIN13 & "" & RESET   #CBA6F7
  ARROW_14R: string = RESET & FG&CATPUCCIN14 & "" & RESET   #74C7EC
  ARROW_15R: string = RESET & FG&CATPUCCIN15 & "" & RESET   #E18B8A


  CIRCLE_0L: string = RESET & FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0    #0D1117  
  CIRCLE_1L: string = RESET & FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1    #45475A  
  CIRCLE_2L: string = RESET & FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2    #585B70 
  CIRCLE_3L: string = RESET & FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3    #F38BA8 
  CIRCLE_4L: string = RESET & FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4    #A6E3A1 
  CIRCLE_5L: string = RESET & FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5    #F9E2AF 
  CIRCLE_6L: string = RESET & FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6    #89B4FA  
  CIRCLE_7L: string = RESET & FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7    #F5C2E7  
  CIRCLE_8L: string = RESET & FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8    #94E2D5 
  CIRCLE_9L: string = RESET & FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9    #A6ADC8 
  CIRCLE_10L: string = RESET & FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10 #FAB387
  CIRCLE_11L: string = RESET & FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11 #F5E0DC
  CIRCLE_12L: string = RESET & FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12 #B4BEFE
  CIRCLE_13L: string = RESET & FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13 #CBA6F7 
  CIRCLE_14L: string = RESET & FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14 #74C7EC 
  CIRCLE_15L: string = RESET & FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15 #E18B8A

  CIRCLE_0R: string = RESET & FG&CATPUCCIN0 & "" & RESET   #0D1117  
  CIRCLE_1R: string = RESET & FG&CATPUCCIN1 & "" & RESET   #45475A  
  CIRCLE_2R: string = RESET & FG&CATPUCCIN2 & "" & RESET   #585B70 
  CIRCLE_3R: string = RESET & FG&CATPUCCIN3 & "" & RESET   #F38BA8 
  CIRCLE_4R: string = RESET & FG&CATPUCCIN4 & "" & RESET   #A6E3A1 
  CIRCLE_5R: string = RESET & FG&CATPUCCIN5 & "" & RESET   #F9E2AF 
  CIRCLE_6R: string = RESET & FG&CATPUCCIN6 & "" & RESET   #89B4FA  
  CIRCLE_7R: string = RESET & FG&CATPUCCIN7 & "" & RESET   #F5C2E7  
  CIRCLE_8R: string = RESET & FG&CATPUCCIN8 & "" & RESET   #94E2D5 
  CIRCLE_9R: string = RESET & FG&CATPUCCIN9 & "" & RESET   #A6ADC8 
  CIRCLE_10R: string = RESET & FG&CATPUCCIN10 & "" & RESET #FAB387
  CIRCLE_11R: string = RESET & FG&CATPUCCIN11 & "" & RESET #F5E0DC
  CIRCLE_12R: string = RESET & FG&CATPUCCIN12 & "" & RESET #B4BEFE
  CIRCLE_13R: string = RESET & FG&CATPUCCIN13 & "" & RESET #CBA6F7 
  CIRCLE_14R: string = RESET & FG&CATPUCCIN14 & "" & RESET #74C7EC 
  CIRCLE_15R: string = RESET & FG&CATPUCCIN15 & "" & RESET #E18B8A
  

  LANGLE_0L: string = RESET & FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0     #0D1117  
  LANGLE_1L: string = RESET & FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1     #3B4252  
  LANGLE_2L: string = RESET & FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2     #434C5E  
  LANGLE_3L: string = RESET & FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3     #F38BA8  
  LANGLE_4L: string = RESET & FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4     #A6E3A1 
  LANGLE_5L: string = RESET & FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5     #F9E2AF 
  LANGLE_6L: string = RESET & FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6     #89B4FA  
  LANGLE_7L: string = RESET & FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7     #F5C2E7 
  LANGLE_8L: string = RESET & FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8     #94E2D5 
  LANGLE_9L: string = RESET & FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9     #A6ADC8 
  LANGLE_10L: string = RESET & FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10  #FAB387 
  LANGLE_11L: string = RESET & FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11  #F5E0DC
  LANGLE_12L: string = RESET & FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12  #B4BEFE 
  LANGLE_13L: string = RESET & FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13  #CBA6F7 
  LANGLE_14L: string = RESET & FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14  #74C7EC 
  LANGLE_15L: string = RESET & FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15  #E18B8A
  
  LANGLE_0R: string = RESET & FG&CATPUCCIN0 & "" & RESET     #0D1117  
  LANGLE_1R: string = RESET & FG&CATPUCCIN1 & "" & RESET     #3B4252  
  LANGLE_2R: string = RESET & FG&CATPUCCIN2 & "" & RESET     #434C5E  
  LANGLE_3R: string = RESET & FG&CATPUCCIN3 & "" & RESET     #F38BA8  
  LANGLE_4R: string = RESET & FG&CATPUCCIN4 & "" & RESET     #A6E3A1 
  LANGLE_5R: string = RESET & FG&CATPUCCIN5 & "" & RESET     #F9E2AF 
  LANGLE_6R: string = RESET & FG&CATPUCCIN6 & "" & RESET     #89B4FA  
  LANGLE_7R: string = RESET & FG&CATPUCCIN7 & "" & RESET     #F5C2E7 
  LANGLE_8R: string = RESET & FG&CATPUCCIN8 & "" & RESET     #94E2D5 
  LANGLE_9R: string = RESET & FG&CATPUCCIN9 & "" & RESET     #A6ADC8 
  LANGLE_10R: string = RESET & FG&CATPUCCIN10 & "" & RESET  #FAB387 
  LANGLE_11R: string = RESET & FG&CATPUCCIN11 & "" & RESET  #F5E0DC
  LANGLE_12R: string = RESET & FG&CATPUCCIN12 & "" & RESET  #B4BEFE 
  LANGLE_13R: string = RESET & FG&CATPUCCIN13 & "" & RESET  #CBA6F7 
  LANGLE_14R: string = RESET & FG&CATPUCCIN14 & "" & RESET  #74C7EC 
  LANGLE_15R: string = RESET & FG&CATPUCCIN15 & "" & RESET  #E18B8A

  RANGLE_0L: string = RESET & FG&CATPUCCIN0 & "" & RESET & BG&CATPUCCIN0     #0D1117  
  RANGLE_1L: string = RESET & FG&CATPUCCIN1 & "" & RESET & BG&CATPUCCIN1     #3B4252  
  RANGLE_2L: string = RESET & FG&CATPUCCIN2 & "" & RESET & BG&CATPUCCIN2     #434C5E  
  RANGLE_3L: string = RESET & FG&CATPUCCIN3 & "" & RESET & BG&CATPUCCIN3     #F38BA8  
  RANGLE_4L: string = RESET & FG&CATPUCCIN4 & "" & RESET & BG&CATPUCCIN4     #A6E3A1 
  RANGLE_5L: string = RESET & FG&CATPUCCIN5 & "" & RESET & BG&CATPUCCIN5     #F9E2AF 
  RANGLE_6L: string = RESET & FG&CATPUCCIN6 & "" & RESET & BG&CATPUCCIN6     #89B4FA  
  RANGLE_7L: string = RESET & FG&CATPUCCIN7 & "" & RESET & BG&CATPUCCIN7     #F5C2E7 
  RANGLE_8L: string = RESET & FG&CATPUCCIN8 & "" & RESET & BG&CATPUCCIN8     #94E2D5 
  RANGLE_9L: string = RESET & FG&CATPUCCIN9 & "" & RESET & BG&CATPUCCIN9     #A6ADC8 
  RANGLE_10L: string = RESET & FG&CATPUCCIN10 & "" & RESET & BG&CATPUCCIN10  #FAB387 
  RANGLE_11L: string = RESET & FG&CATPUCCIN11 & "" & RESET & BG&CATPUCCIN11  #F5E0DC
  RANGLE_12L: string = RESET & FG&CATPUCCIN12 & "" & RESET & BG&CATPUCCIN12  #B4BEFE 
  RANGLE_13L: string = RESET & FG&CATPUCCIN13 & "" & RESET & BG&CATPUCCIN13  #CBA6F7 
  RANGLE_14L: string = RESET & FG&CATPUCCIN14 & "" & RESET & BG&CATPUCCIN14  #74C7EC 
  RANGLE_15L: string = RESET & FG&CATPUCCIN15 & "" & RESET & BG&CATPUCCIN15  #E18B8A
  
  RANGLE_0R: string = RESET & FG&CATPUCCIN0 & "" & RESET     #0D1117  
  RANGLE_1R: string = RESET & FG&CATPUCCIN1 & "" & RESET     #3B4252  
  RANGLE_2R: string = RESET & FG&CATPUCCIN2 & "" & RESET     #434C5E  
  RANGLE_3R: string = RESET & FG&CATPUCCIN3 & "" & RESET     #F38BA8  
  RANGLE_4R: string = RESET & FG&CATPUCCIN4 & "" & RESET     #A6E3A1 
  RANGLE_5R: string = RESET & FG&CATPUCCIN5 & "" & RESET     #F9E2AF 
  RANGLE_6R: string = RESET & FG&CATPUCCIN6 & "" & RESET     #89B4FA  
  RANGLE_7R: string = RESET & FG&CATPUCCIN7 & "" & RESET     #F5C2E7 
  RANGLE_8R: string = RESET & FG&CATPUCCIN8 & "" & RESET     #94E2D5 
  RANGLE_9R: string = RESET & FG&CATPUCCIN9 & "" & RESET     #A6ADC8 
  RANGLE_10R: string = RESET & FG&CATPUCCIN10 & "" & RESET  #FAB387 
  RANGLE_11R: string = RESET & FG&CATPUCCIN11 & "" & RESET  #F5E0DC
  RANGLE_12R: string = RESET & FG&CATPUCCIN12 & "" & RESET  #B4BEFE 
  RANGLE_13R: string = RESET & FG&CATPUCCIN13 & "" & RESET  #CBA6F7 
  RANGLE_14R: string = RESET & FG&CATPUCCIN14 & "" & RESET  #74C7EC 
  RANGLE_15R: string = RESET & FG&CATPUCCIN15 & "" & RESET  #E18B8A
  

#[
[settings]
  # Window settings - CATPUCCIN type theme
  borderWidth = 1
  borderColorUnfocused = "#585b70"
  borderColorFocused = "#f5c2e7"
  borderColorUrgent = "#f38ba8"
  # Bar settings
  barHeight = 26
  windowTitlePosition = "center"
  barBackgroundColor = "#45475a"
  barForegroundColor = "#0d1117"
  barSelectionColor = "#b4befe"
  barUrgentColor = "#f38ba8"
  barFonts = [
    "DejaVu Sans:style=Bold:size=10:antialias=true",
    "FontAwesome:size=14:antialias=true",
    "JetBrainsMono Nerd Font:size=16:antialias=true",
  ]
]#




